def rn_pods

end

target 'teethSnapshot' do
  platform :ios, '9.0'
  rn_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
  end
end
